---
abstract: 'non-blocking access'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-Google-PageRank
provides:
  POE::Component::IRC::Plugin::Google::PageRank:
    file: lib/POE/Component/IRC/Plugin/Google/PageRank.pm
    version: 0.02
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::IRC::Plugin: 0.09
  POE::Component::WWW::Google::PageRank: 0.01
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
